# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: apiclient
output: ./apiclient.gen.go
generate:
  models: true
  client: true
output-options:
  resolve-type-name-collisions: true
  generate-types-for-anonymous-schemas: true
  type-mapping:
    integer:
      default:
        type: int64
  overlay:
    path: overlay.yaml
    strict: true
