// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_porkbun

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func PorkbunProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"api_key": schema.StringAttribute{
				Optional:            true,
				Sensitive:           true,
				Description:         "The API key for the Porkbun account. It can be sourced from the `PORKBUN_API_KEY` environment variable.",
				MarkdownDescription: "The API key for the Porkbun account. It can be sourced from the `PORKBUN_API_KEY` environment variable.",
			},
			"base_url": schema.StringAttribute{
				Optional:            true,
				Description:         "The base URL for the Porkbun API. Defaults to `https://api.porkbun.com/api/json`. It can be sourced from the `PORKBUN_BASE_URL` environment variable.",
				MarkdownDescription: "The base URL for the Porkbun API. Defaults to `https://api.porkbun.com/api/json`. It can be sourced from the `PORKBUN_BASE_URL` environment variable.",
			},
			"secret_key": schema.StringAttribute{
				Optional:            true,
				Sensitive:           true,
				Description:         "The secret API key for the Porkbun account. It can be sourced from the `PORKBUN_SECRET_KEY` environment variable.",
				MarkdownDescription: "The secret API key for the Porkbun account. It can be sourced from the `PORKBUN_SECRET_KEY` environment variable.",
			},
		},
		MarkdownDescription: "The Porkbun provider is used to interact with the Porkbun service.\n\nIf you find this provider useful, please consider supporting me through GitHub Sponsorship or Ko-Fi to help with its development.\n\n[![Github-sponsors](https://img.shields.io/badge/sponsor-30363D?style=for-the-badge&logo=GitHub-Sponsors&logoColor=#EA4AAA)](https://github.com/sponsors/jianyuan)\n[![Ko-Fi](https://img.shields.io/badge/Ko--fi-F16061?style=for-the-badge&logo=ko-fi&logoColor=white)](https://ko-fi.com/L3L71DQEL)",
	}
}

type PorkbunModel struct {
	ApiKey    types.String `tfsdk:"api_key"`
	BaseUrl   types.String `tfsdk:"base_url"`
	SecretKey types.String `tfsdk:"secret_key"`
}
